Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "The VPC Id"
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: "The Subnet Id"
Resources:
  SampleEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-e251209a
      InstanceType: t2.micro
      KeyName: us-west-2
      SubnetId: !Ref 'SubnetId'
      SecurityGroupIds: 
        - !Ref 'SampleSG'
  SampleSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref 'VpcId'
      GroupDescription: 'SG Created through cloudformation'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 8.33.33.47/32




  


