Resources:
  Website:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        RoutingRules:
          - 
            RoutingRuleCondition:
              HttpErrorCodeReturnedEquals: 404
            RedirectRule:
              ReplaceKeyWith: index.html
      Tags:
        - 
          Key: Name
          Value: test-website
